collections:
  a:
    label: a
    output: true
    permalink: /:collection/:name
    layout: default
  b:
    label: b
    output: true
    permalink: /:collection/:name
    layout: default
  r:
    label: r
    output: true
    permalink: /:collection/:name
    layout: recipe
  p:
    label: p
    output: true
    permalink: /:collection/:name
    layout: default
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
